---
title: "PCA Programación SIG"
output: html_document
date: "2025-03-03"
---

```{r}
library(sf)
library(dplyr)
geo_data <- st_read("/Users/jorgeandresjolahernandez/Desktop/Programacion SIG/Proyecto/Project_SIG/results/edafoclima.geojson")
df_edafoclim <- geo_data %>% st_drop_geometry()


df_edafoclim

pca_result=prcomp(df_edafoclim[,-c(1,10,11)], scale. = TRUE)
# Calcular la varianza explicada
explained_var <- pca_result$sdev^2 / sum(pca_result$sdev^2)


library(factoextra)

# Biplot SOLO con las variables
fviz_pca_var(pca_result, col.var = "red", repel = TRUE)

```
```{r}
# Gráfico de la varianza explicada
barplot(explained_var * 100, 
        names.arg = paste0("PC", 1:length(explained_var)), 
        las = 2, col = "steelblue",
        ylab = "Explained Variance (%)",
        main = "Explained Variance by Each Principal Component")

```

```{r}
fviz_contrib(pca_result, choice = "var", axes = 1, top = 10) 
fviz_contrib(pca_result, choice = "var", axes = 2, top = 10) 
fviz_contrib(pca_result, choice = "var", axes = 3, top = 10) 
```
```{r}
df_pca <- as.data.frame(cbind(COD=df_edafoclim$CODIGO,pca_result$x[, 1:3]))  # Mantener solo PC1 y PC2

df_pca$x=df_edafoclim$x
df_pca$y=df_edafoclim$y
```
```{r}
library(writexl)
write.csv(df_pca, "/Users/jorgeandresjolahernandez/Desktop/Programacion SIG/Proyecto/Project_SIG/src/appResults/pca_results.csv", row.names = FALSE)
```

```{r}
library(readxl)
datos=read_csv("/Users/jorgeandresjolahernandez/Desktop/Programacion SIG/Proyecto/Project_SIG/src/appResults/pca_results.csv")
datos
```
```{r}
cuanti=datos
xy <- cuanti %>% select(x, y)
cuanti <- cuanti[, -c(1, 5, 6)]
cuanti=scale(cuanti)
D0 <- dist(cuanti)  # Distancias socioeconómicas
D1 <- dist(xy)  # Distancias espaciales

range.alpha <- seq(0, 1, 0.1)
cr <- choicealpha(D0, D1, range.alpha, 5, graph = FALSE)
# Guardamos el gráfico como imagen
plot_path <- "plot_image.png"  # Especifica la ruta de la imagen
png(plot_path, width = 800, height = 900)  # Guardamos el gráfico como PNG
plot(cr)  # Aquí generamos el gráfico


tree <- hclustgeo(D0, D1, alpha = 0.8)
P5bis <- cutree(tree, 5)

```

```{r}
unique(datos$COD)
df_cluster=data.frame(CODIGO=df_edafoclim$CODIGO,clust=P5bis)
write_csv(df_cluster,"/Users/jorgeandresjolahernandez/Desktop/Programacion SIG/Proyecto/Project_SIG/results/clusters.csv")
```




